from django.db import models


class BidInformation(models.Model):
    ref_id = models.IntegerField()
    ref_no = models.IntegerField()
    stage = models.IntegerField()
    stage2_ref_id = models.IntegerField()
    org_id = models.ForeignKey('Organization', to_field='org_id')
    classification = models.CharField(blank=True)
    solicitation_no = models.CharField(blank=True)
    notice_type = models.CharField(blank=True)
    business_category = models.CharField(blank=True)
    procurement_mode = models.CharField(blank=True)
    funding_instrument = models.CharField(blank=True)
    funding_source = models.CharField(blank=True)
    approved_budget = models.FloatType(null=False, blank=False)
    publish_date = models.DateTimeField(null=False, blank=False)
    closing_date = models.DateTimeField(null=False, blank=False)
    contract_duration = models.IntegerField(null=True)
    calendar_type = models.CharField(blank=True)
    trade_agreement = models.CharField(blank=True)
    pre_bid_date = models.DateTimeField(null=False, blank=False)
    pre_bid_venue = models.CharField(blank=True)
    procuring_entity_org_id = models.ForeignKey('Organization', to_field='org_id')
    procuring_entity_org = models.CharField(blank=True)
    client_agency_org_id = models.ForeignKey('Organization', to_field='org_id')
    client_agency_org = models.CharField(blank=True)
    contact_person = models.CharField(blank=True)
    contact_person_address = models.TextField(blank=True)
    tender_title = models.CharField(blank=True)
    description = models.TextField(blank=True)
    other_info = models.TextField(blank=True)
    tender_status = models.CharField(blank=True)
    reason = models.TextField(blank=True)
    date_available = models.DateTime(null=True, blank=True)
    collection_contact = models.CharField(blank=True)
    collection_point = models.CharField(blank=True)
    special_instruction = models.TextField(blank=True)
    created_by = models.CharField()
    creation_date = models.DateTimeField()
    modified_date = models.DateTimeField()

    def __unicode__(self):
        return "{}: {} {}".format(ref_id, notice_type, business_category)

