# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('masteritems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('award_id', models.PositiveIntegerField(unique=True)),
                ('award_title', models.CharField(max_length=2048, blank=True)),
                ('publish_date', models.DateTimeField(null=True)),
                ('previous_award_id', models.PositiveIntegerField(null=True)),
                ('item_name', models.CharField(max_length=2048, blank=True)),
                ('item_description', models.TextField()),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('uom', models.CharField(max_length=2048, blank=True)),
                ('budget', models.FloatField()),
                ('unspc_code', models.CharField(max_length=2048, blank=True)),
                ('unspc_description', models.TextField()),
                ('awardee', models.CharField(max_length=2048, blank=True)),
                ('award_type', models.CharField(max_length=2048, blank=True)),
                ('contract_amt', models.FloatField()),
                ('award_date', models.DateTimeField(null=True)),
                ('award_reason', models.CharField(max_length=2048, blank=True)),
                ('contract_no', models.CharField(max_length=2048, blank=True)),
                ('proceed_date', models.DateTimeField(null=True)),
                ('contract_start_date', models.DateTimeField(null=True)),
                ('contract_end_date', models.DateTimeField(null=True)),
                ('is_short_list', models.IntegerField(null=True)),
                ('is_re_award', models.IntegerField(null=True)),
                ('is_amp', models.IntegerField(null=True)),
            ],
            bases=(models.Model, core.models.SelfAwareModelMixin),
        ),
        migrations.CreateModel(
            name='BiddersList',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bidder_name', models.CharField(max_length=2048)),
                ('modified_date', models.DateTimeField(null=True)),
                ('award_id', models.ForeignKey(to='philgeps.Awards', to_field=b'award_id', null=True)),
            ],
            bases=(models.Model, core.models.SelfAwareModelMixin),
        ),
        migrations.CreateModel(
            name='BidInformation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ref_id', models.IntegerField(unique=True)),
                ('ref_no', models.CharField(max_length=2048, blank=True)),
                ('stage', models.IntegerField(null=True)),
                ('stage2_ref_id', models.CharField(max_length=2048, blank=True)),
                ('classification', models.CharField(max_length=2048, blank=True)),
                ('solicitation_no', models.CharField(max_length=2048, blank=True)),
                ('notice_type', models.CharField(max_length=2048, blank=True)),
                ('business_category', models.CharField(max_length=2048, blank=True)),
                ('procurement_mode', models.CharField(max_length=2048, blank=True)),
                ('funding_instrument', models.CharField(max_length=2048, blank=True)),
                ('funding_source', models.CharField(max_length=2048, blank=True)),
                ('approved_budget', models.FloatField(null=True)),
                ('publish_date', models.DateTimeField(null=True)),
                ('closing_date', models.DateTimeField(null=True)),
                ('contract_duration', models.IntegerField(null=True)),
                ('calendar_type', models.CharField(max_length=2048, blank=True)),
                ('trade_agreement', models.CharField(max_length=2048, blank=True)),
                ('pre_bid_date', models.DateTimeField(null=True)),
                ('pre_bid_venue', models.CharField(max_length=2048, blank=True)),
                ('procuring_entity_org', models.CharField(max_length=2048, blank=True)),
                ('client_agency_org', models.CharField(max_length=2048, blank=True)),
                ('contact_person', models.CharField(max_length=2048, blank=True)),
                ('contact_person_address', models.TextField(blank=True)),
                ('tender_title', models.CharField(max_length=2048, blank=True)),
                ('description', models.TextField(blank=True)),
                ('other_info', models.TextField(blank=True)),
                ('tender_status', models.CharField(max_length=2048, blank=True)),
                ('reason', models.TextField(blank=True)),
                ('date_available', models.DateTimeField(null=True, blank=True)),
                ('collection_contact', models.CharField(max_length=2048, blank=True)),
                ('collection_point', models.CharField(max_length=2048, blank=True)),
                ('special_instruction', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=2048)),
                ('creation_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            bases=(models.Model, core.models.SelfAwareModelMixin),
        ),
        migrations.CreateModel(
            name='BidLineItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('line_item_id', models.PositiveIntegerField(unique=True, null=True)),
                ('item_name', models.CharField(max_length=2048, null=True, blank=True)),
                ('item_description', models.TextField(null=True, blank=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('uomid', models.PositiveIntegerField(null=True)),
                ('uom', models.CharField(max_length=2048, null=True, blank=True)),
                ('budget', models.FloatField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('ref_id', models.ForeignKey(to='philgeps.BidInformation', to_field=b'ref_id', null=True)),
            ],
            bases=(models.Model, core.models.SelfAwareModelMixin),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('org_id', models.PositiveIntegerField(unique=True)),
                ('member_type_id', models.PositiveIntegerField(null=True)),
                ('member_type', models.CharField(max_length=2048, blank=True)),
                ('parent_org_id', models.PositiveIntegerField(null=True)),
                ('is_org_foreign', models.NullBooleanField()),
                ('org_name', models.CharField(max_length=2048, blank=True)),
                ('goverment_branch', models.CharField(max_length=2048, blank=True)),
                ('government_organization_type', models.CharField(max_length=2048, blank=True)),
                ('supplier_form_of_organization', models.CharField(max_length=2048, blank=True)),
                ('supplier_organization_type', models.CharField(max_length=2048, blank=True)),
                ('org_reg_date', models.DateTimeField(null=True)),
                ('website', models.URLField(blank=True)),
                ('org_description', models.TextField(blank=True)),
                ('country_code', models.CharField(max_length=2, blank=True)),
                ('country', models.CharField(max_length=2048, blank=True)),
                ('region', models.CharField(max_length=2048, blank=True)),
                ('province', models.CharField(max_length=2048, blank=True)),
                ('city', models.CharField(max_length=2048, blank=True)),
                ('address1', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('address3', models.TextField(blank=True)),
                ('zip_code', models.CharField(max_length=2048, blank=True)),
                ('org_status', models.CharField(max_length=2048, blank=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            bases=(models.Model, core.models.SelfAwareModelMixin),
        ),
        migrations.CreateModel(
            name='ResourceAPIMap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('api_endpoint', models.CharField(max_length=2048, blank=True)),
                ('source_model', models.OneToOneField(to='contenttypes.ContentType')),
            ],
            bases=(models.Model, core.models.SelfAwareModelMixin),
        ),
        migrations.AddField(
            model_name='bidinformation',
            name='client_agency_org_id',
            field=models.ForeignKey(related_name='client_bid_information', to_field=b'org_id', to='philgeps.Organization', null=True),
        ),
        migrations.AddField(
            model_name='bidinformation',
            name='org_id',
            field=models.ForeignKey(related_name='bid_information', to_field=b'org_id', to='philgeps.Organization', null=True),
        ),
        migrations.AddField(
            model_name='bidinformation',
            name='procuring_entity_org_id',
            field=models.ForeignKey(related_name='procuring_bid_information', to_field=b'org_id', to='philgeps.Organization', null=True),
        ),
        migrations.AddField(
            model_name='bidderslist',
            name='line_item_id',
            field=models.ForeignKey(to='philgeps.BidLineItem', to_field=b'line_item_id', null=True),
        ),
        migrations.AddField(
            model_name='bidderslist',
            name='org_id',
            field=models.ForeignKey(to='philgeps.Organization', to_field=b'org_id', null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='awardee_id',
            field=models.ForeignKey(to='philgeps.Organization', to_field=b'org_id', null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='line_item_id',
            field=models.ForeignKey(to='philgeps.BidLineItem', to_field=b'line_item_id', null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='master_item',
            field=models.ForeignKey(related_name='awards_set', blank=True, to='masteritems.MasterItem', null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='ref_id',
            field=models.ForeignKey(to='philgeps.BidInformation', to_field=b'ref_id', null=True),
        ),
    ]
